export const GET_ALL_TASKS_FROM_API_REQUEST = "GET_ALL_TASKS_FROM_API_REQUEST";
export const GET_ALL_TASKS_FROM_API_FAIL = "GET_ALL_TASKS_FROM_API_FAIL";
export const GET_ALL_TASKS_FROM_API_SUCCESS = "GET_ALL_TASKS_FROM_API_SUCCESS";
