export const GET_ALL_TASKS_FROM_API_REQUEST = "GET_ALL_TASKS_FROM_API_REQUEST";
export const GET_ALL_TASKS_FROM_API_FAIL = "GET_ALL_TASKS_FROM_API_FAIL";
export const GET_ALL_TASKS_FROM_API_SUCCESS = "GET_ALL_TASKS_FROM_API_SUCCESS";

export const DELETE_TASK_SUCCESS = "DELETE_TASK_SUCCESS";
export const CHANGE_TASK_STATUS_SUCCESS = "CHANGE_TASK_STATUS_SUCCESS";
